language: java
jdk:
- oraclejdk8

notifications:
  slack:
    rooms:
      secure: HxrF1m7dSi+gSAAqHtV9+a4DO6T2ggRTxzJ3F8lJRgnA+mPj7uoOfyoUVipf6G0YNAGqeV6mDsvM1U//qEAgoUOUxLwCc8xvEu5moF8oiAuYDoEVBE/JZeiUGMZ7/xcqt9WlS7ef4uMNeN9BDIhnlCZs4IjXHUuRUFDsWquleFo=

sudo: false

