mongo:
  image: mongo:latest

postgres:
  build: resources/rdbms/postgresql

authorizationserver:
  build: authorization-server/docker
  links:
    - mongo:omh-mongo
    - postgres:omh-postgres
  ports:
    - "8082:8082"

resourceserver:
  build: resource-server/docker
  links:
    - mongo:omh-mongo
    - postgres:omh-postgres
  ports:
    - "8083:8083"
